apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    environment: shared
    owner: platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
